package com.example.app.common.config;

import io.micrometer.core.instrument.MeterRegistry;
import org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration for Micrometer metrics collection and reporting.
 * 
 * <p>This configuration sets up common tags for all metrics, allowing metrics
 * to be filtered and grouped by application name. Metrics can be exported
 * to various monitoring systems (Prometheus, CloudWatch, etc.) via Spring Boot Actuator.
 * 
 * <p><b>Common Tags:</b>
 * <ul>
 *   <li>application: "multi-module-app" (identifies this application in metrics)</li>
 * </ul>
 * 
 * <p><b>Usage:</b> Metrics are automatically collected for HTTP requests, database
 * operations, and custom counters/gauges. Access metrics via /actuator/metrics endpoint
 * (if Actuator is configured).
 * 
 * @author Generated
 * @since 1.0.0
 */
@Configuration
public class MetricsConfig {

    /**
     * Customizes the Micrometer MeterRegistry with common tags.
     * 
     * <p>All metrics generated by this application will include the "application"
     * tag, making it easy to filter metrics in monitoring dashboards.
     * 
     * @return MeterRegistryCustomizer that adds common tags
     */
    @Bean
    public MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> registry.config()
            .commonTags("application", "multi-module-app");
    }
}

